"""
Tests for the filter implementations.
"""

import pytest
import numpy as np
from direct_path_cancellation.simulation import simulate_scenario
from direct_path_cancellation.filters import WienerFilter, LMSFilter

@pytest.fixture
def simple_scenario():
    """A simple scenario with a known delay and attenuation."""
    n_samples = 1024
    filter_length = 32
    delay = 10

    # Create a random signal
    x = np.random.randn(n_samples) + 1j * np.random.randn(n_samples)

    # Create a delayed and attenuated version for the second channel
    d = np.zeros_like(x)
    d[delay:] = 0.5 * x[:-delay]

    return x, d, filter_length, delay

@pytest.fixture
def realistic_scenario():
    """A more realistic scenario generated by the simulation module."""
    channel1, channel2, target_signal = simulate_scenario(
        n_samples=4096,
        fs=1e6,
        snr_db=30,
        target_delay_s=50e-6,
        target_doppler_hz=100,
        transmit_power_w=1000,
        antenna_gain_db=20,
        radar_cross_section_m2=1,
        frequency_hz=10e9,
        target_range_m=5000,
        seed=42,
    )
    return channel1, channel2, target_signal

def test_wiener_filter_unit(simple_scenario):
    """
    Tests the WienerFilter on a simple, known scenario.
    The filter should learn the simple delay and attenuation.
    """
    x, d, filter_length, delay = simple_scenario

    # Initialize and run the filter
    wiener_filter = WienerFilter(filter_length=filter_length)
    cleaned_signal = wiener_filter(x, d)

    # The weights should have a peak at the delay index
    assert np.argmax(np.abs(wiener_filter.weights)) == delay
    # The magnitude of the peak should be close to the attenuation
    assert np.isclose(np.abs(wiener_filter.weights[delay]), 0.5, atol=1e-2)

def test_wiener_filter_integration(realistic_scenario):
    """
    Tests the WienerFilter on a realistic scenario.
    It should significantly reduce the power of the interference.
    """
    channel1, channel2, _ = realistic_scenario
    filter_length = 64

    # Initialize and run the filter
    wiener_filter = WienerFilter(filter_length=filter_length)
    cleaned_signal = wiener_filter(channel1, channel2)

    # Calculate power before and after
    power_before = np.mean(np.abs(channel2)**2)
    power_after = np.mean(np.abs(cleaned_signal)**2)

    # Check that power is significantly reduced (e.g., by 10 dB)
    cancellation_db = 10 * np.log10(power_before / power_after)
    assert cancellation_db > 10

def test_lms_filter_unit(simple_scenario):
    """
    Tests the LMSFilter on a simple, known scenario.
    The filter should learn the simple delay and attenuation.
    """
    x, d, filter_length, delay = simple_scenario

    # Initialize the filter
    lms_filter = LMSFilter(filter_length=filter_length, learning_rate=0.01)

    # Run the filter for a few epochs to let it converge
    for _ in range(10):
        _ = lms_filter(x, d)

    # The weights should have a peak at the delay index
    assert np.argmax(np.abs(lms_filter.weights)) == delay
    # The magnitude of the peak should be close to the attenuation
    assert np.isclose(np.abs(lms_filter.weights[delay]), 0.5, atol=0.1)

def test_lms_filter_integration(realistic_scenario):
    """
    Tests the LMSFilter on a realistic scenario.
    It should significantly reduce the power of the interference.
    """
    channel1, channel2, _ = realistic_scenario
    filter_length = 64

    # Initialize the filter
    lms_filter = LMSFilter(filter_length=filter_length, learning_rate=0.5)

    # Run the filter for a few epochs to let it converge
    for _ in range(5):
        cleaned_signal = lms_filter(channel1, channel2)

    # Calculate power before and after
    power_before = np.mean(np.abs(channel2)**2)
    power_after = np.mean(np.abs(cleaned_signal)**2)

    # Check that power is significantly reduced (e.g., by 10 dB)
    cancellation_db = 10 * np.log10(power_before / power_after)
    assert cancellation_db > 10
